Refactor/92 consistent design
virto-network/website pull request #93
Opened 2023-11-21 14:45 UTC by ail3ngrimaldi

This PR:

- Consolidates general configurations previously placed across specific files into a single universal page file.
- Implements the `<article>` tag for maintaining a consistent structure and ensures uniform margins and spacing between elements.
- Removes deprecated classes and those no longer necessary due to the new general configurations.
- Addresses spacing issues in the `blog.liquid` file.
- Transfers the .`scroll-down-link` class to the general layout file to ensure its appearance across all sections. Moves css properties for `.scroll-up-link`to `common.css` To-do: Adjust visibility of the arrow in sections with a dark background color and smaller screens, need some help here.
- Transfers the `.cta` class from specific files to common.css
- Updates the url in `about.liquid` and  added links in the footer.
- Moves listed content to the `index.yml` file.

PS: commit 87787a051130ed64799b701654c3077690c308c8 resolves #72 by fixing the spacing issue in blog image and title and oldest post cards, but #76 issue was treated as well (excessive space between sections).

2023-11-21 18:51 UTC, olanod approved these changes

2023-11-21 18:51 UTC, olanod commented on _includes/build_machine.svg
Is it the same picture in `img/build_machine.svg`? why not use that one?

2023-11-21 18:54 UTC, olanod requested changes
There seems to be a regression with the blog posts that are no longer centered

2023-11-22 18:17 UTC, ail3ngrimaldi commented
Both things were solved posts: 34949103db18a2c46196dcf3a7481eb7b3aa425d and image: 357be99fdbb3ef08472680ef46c4172c1b89e5a1

Please let me know it there's anything else that could be improved :)

2023-11-24 09:01 UTC, olanod approved these changes

2023-11-24 09:02 UTC, merged